name: Model Validation

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
        
    - name: Validate model parameters
      run: |
        python -c "
        from model import MNISTNet
        import torch
        
        model = MNISTNet()
        total_params = sum(p.numel() for p in model.parameters())
        
        # Check parameter count
        assert total_params < 20000, f'Model has {total_params} parameters, should be less than 20000'
        
        # Check for BatchNorm
        has_bn = any(isinstance(m, torch.nn.BatchNorm2d) for m in model.modules())
        assert has_bn, 'Model should use BatchNormalization'
        
        # Check for Dropout
        has_dropout = any(isinstance(m, torch.nn.Dropout) for m in model.modules())
        assert has_dropout, 'Model should use Dropout'
        
        # Check for GAP or FC
        has_gap = any(isinstance(m, torch.nn.AdaptiveAvgPool2d) for m in model.modules())
        has_fc = any(isinstance(m, torch.nn.Linear) for m in model.modules())
        assert has_gap or has_fc, 'Model should use either GAP or Fully Connected layer'
        
        print('All validation checks passed!')
        " 